# Generated by Django 2.2.4 on 2019-08-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='username',
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=255, primary_key=True, serialize=False),
        ),
    ]
